### ISSUE TITLE
Adjuntar consultas del mismo caso

### ISSUE THREAD

**Issue by frustratedcup** [omelendrez/medical-record-fe#116]
Descripción
--
Existe el caso en el que el que hay varias consultas referidas al mismo caso.
Podríamos agregar una funcionalidad que permita adjuntar consultas del mismo paciente cuando tienen el mismo **Diagnostico**.

Tareas
--
Discutir sobre opciones de implementación de la solución requerida.

**Comment by omelendrez** [comment]
Done
