### ISSUE TITLE
Creación de nuevos campo para consultas (vacunacion, desparacitacion)

### ISSUE THREAD

**Issue by frustratedcup** [omelendrez/medical-record-fe#122]
Descripción
--
En algunos casos, los pacientes no tienen una consulta, sino que reciben una vacunacion o desparacitacion. Se seccionaran los componentes para que aparezca **Consulta** con todos los campos anteriores. **Vacunacion** y **Desparacitacion**, cada uno con un campo nuevo.

Tarea 
--
- Seccionar en **Consulta**, **Vacunacion** y **Desparacitacion** con sus respectivos titulos los siguientes componentes:
  - *components/consultations/ConsultationAdd.jsx*
  - *components/consultations/ConsultationEdit.jsx*
- Agregar dos nuevos campos en los siguientes componentes que irian cada uno debajo de **Vacunacion** y **Desparacitacion** en:
  - *components/consultations/ConsultationAdd.jsx*
  - *components/consultations/ConsultationEdit.jsx*
Agregar los dos nuevos campos a la variable de estado `form`.

**Comment by omelendrez** [comment]
Cambio de paradigma
