### ISSUE TITLE
Crear formulario de edición de registro de vacunación

### ISSUE THREAD

**Issue by omelendrez** [omelendrez/medical-record-fe#131]
Detalles
--
Se deberá copiar el estilo de `ConsultationEdit` 

Tareas
--
El nuevo componente se creará en la siguiente URL
- `components/vaccinations/VaccinationEdit.jsx`

**Comment by frustratedcup** [comment]
Seria Vaccination o Vacunation?

**Comment by omelendrez** [comment]
> Seria Vaccination o Vacunation?

Vaccination. The other word doesn't exist.
