### ISSUE TITLE
Modificar selección de vacunas

### ISSUE THREAD

**Issue by frustratedcup** [omelendrez/medical-record-fe#134]
Detalles
--
Se deberán modificar los formularios `VaccinationEdit` y `VaccinationAdd` para que, en vez de un input text, haya una seleccián de distintas vacunas.

Tareas
--
- En `services/utils.js`: 
1.  Copiar y pegar `paymentMethods` en utils.
2. Modificar para que sea referido a la lista de vacunaciones.
La lista de opciones será:

| id| name |
| --- | --- |
| 1 | Triple felina |
| 2 | Quíntuple |
| 3 | Séxtuple |
| 4 | Puppy DP |
| 5 | Antirrábica |

- En `VaccinationAdd.jsx` : 
1.  Importar el listado hecho en el paso anterior de `services/utils.js` para utilizarlo.
2. Copiar el `select` y el `label` que aparece en el componente **ConsultationAdd.jsx** para listar formas de pago. Pegarlo en **VaccinationAdd.jsx**.
3. Modificarlo para utilizar la lista importada.
4. Agregar el nuevo campo creado al `form`.

-  En `VaccinationEdit.jsx` : 
1. Importar el listado recientemente usado de `services/utils.js` .
2. Copiar el `select` y el `label` que aparece en el componente **VaccinationAdd.jsx**. Pegarlo en **VaccinationEdit.jsx**.
3. Modificarlo para utilizar la lista importada.
4. Agregar el nuevo campo creado al `form`.

**Comment by omelendrez** [comment]
@frustratedcup se puede elegir sólo una vacuna a la vez o más de una?
Por ejemplo, cuando el cliente trae un animal a vacunar, se le pone sólo una vacuna o puede ser más de una?
