### ISSUE TITLE
Agregar nuevas entradas a la barra de navegación

### ISSUE THREAD

**Issue by frustratedcup** [omelendrez/medical-record-fe#138]
Descripción
--
Se deberán mostrar los componentes de **Vaccinations** y **Dewormings** para ingresar en la barra de navegación.

Tareas
--

- En `App.js`

1. Importar los componentes **Vaccinations** y **Dewormings**.
2. Agregar en el `Switch` los `Route` para `/vacunaciones` y `/desparasitaciones`, utilizando los componentes recientemente importados.

- En `NavBar.jsx`

1. Agregar los `NavLink` para `/vacunaciones` y `/desparasitaciones`, luego de `/consultas` .

**Comment by omelendrez** [comment]
Done
