### ISSUE TITLE
Modificación en la lista de sexos

### ISSUE THREAD

**Issue by omelendrez** [omelendrez/medical-record-fe#97]
Descripción
--
Luego de verificar la aplicación con Angie me aclaró que lo que estaban poniendo en el sexo del animal era correcto y corresponde a la siguiente clasificación:
H o He - Hembra entera, M o Me - Macho entero, Hc - Hembra castrada y Mc - Macho castrado

Tareas
--
Cambiar las opciones de sexo que está en *services/utils* por las siguientes:
| id| name |
| --- | --- |
| Hc | Hembra castrada |
| He | Hembra entera |
| Mc | Macho castrado |
| Me | Macho entero |

**Comment by frustratedcup** [comment]
¿Se debería mostrar como "Hembra entera" o directamente "He"?

**Comment by omelendrez** [comment]
Preguntale a Angie cómo lo quiere ver.
