### ISSUE TITLE
Fecha de nacimiento debe ser campo tipo fecha

### ISSUE THREAD

**Issue by omelendrez** [omelendrez/medical-record-fe#99]
Descripción
--
Angie quiere que el campo para cargar la fecha de nacimiento del paciente sea un campo tipo fecha, para que pueda calcular automáticamente la edad.
Aquellas fechas desconocidas o donde el sólo se sabe el año o el año y el mes pero no el día, se cargará una fecha inventada.
Por ejemplo si sólo se sabe el año se cargará *01/01/año*
Si se sabe el mes y el año se cargará *01/mes/año*

Tareas
--
- Cambiar el tipo de input al campo `yearBorn` de `<input type="text"` a `<input type="date"` en los siguientes componentes:
  - *components/pets/PetAdd.jsx*
  - *components/pets/PetEdit.jsx*

**Comment by frustratedcup** [comment]
¿Es necesario también mostrar la edad teniendo en cuenta la fecha o es simplemente el input de fecha?

**Comment by omelendrez** [comment]
Buena pregunta, creo que deberíamos mostrar la edad en todos lados en lugar de mostrar las fechas
